<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>

		<!-- Core Package Metadata -->
		<PackageId>Bikiran.Validation</PackageId>
		<Version>1.0.9</Version>
		<Authors>bishojit</Authors>
		<Company>BIKIRAN</Company>
		<Description>A comprehensive .NET validation library providing robust utilities for validating emails, URLs, IP addresses, phone numbers, user credentials, file formats, server names, domains, dates, and more. Features customizable error messages, optional field support, and regex-powered validation.</Description>
		<PackageTags>validation;form-validation;email-validation;url-validation;ip-validation;phone-validation;password-validation;username-validation;dotnet;csharp;data-validation;input-validation;server-validation;domain-validation</PackageTags>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!-- Add below existing PackageTags -->
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<!-- Add NuGet.Protocol package reference -->
		<PackageReference Include="NuGet.Protocol" Version="6.13.2" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="Phone\countries.json" Pack="true" PackagePath="contentFiles\any\any\Phone\" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Phone\countries.json" />
	</ItemGroup>
</Project>
